# fly.toml app configuration file generated for exocosmos-db on 2025-05-20T19:40:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exocosmos-db'
primary_region = 'cdg'

[build]
image = 'mysql:8'

[env]
MYSQL_DATABASE = 'exocosmos'

[[mounts]]
source = 'mysqldata'
destination = '/var/lib/mysql'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
